### ISSUE TITLE
CGPoint type suggest pixel coordinates

### ISSUE THREAD

**Issue by karstenBriksoft** [nst/ShapefileReader#1]
It seems you are using CGPoint as type for the coordinates of the shape file. I’d assume CGPoints are pixel coordinates, not map-coordinates. Wouldn't it be better to introduce a ShpPoint or something for that task?

**Comment by nst** [comment]
Just to make it clear, here is how the reading of points currently works:
- the ShapefileReader class has a shp property of type SHPReader
- the SHPReader method shapeGenerator() will return arrays of CGPoints, in map coordinates
- it's up to the user to decide if and how she will draw the points

And here is how the sample drawing code draws the points. (Another project may do differently.)
- the sample code creates a subclass of BitmapCanvas called BitmapCanvasShapefile
- BitmapCanvasShapefile method shape() will actually draw the points
- before drawing the points, shape() performs geo. transforms to match the shape bounding box
- these transforms actually map the map coordinates to the pixel coordinates

Now, we could make SHPReader().shapeGenerator() return lists of Double instead of CGPoints, but the user would have to convert into CGPoints at some points, so I'd prefer keeping CGPoints.

Also, I found that returning [CGPoint] and using geometric transforms was the most elegant way to do map map coordinates to pixel coordinates, but if there's a better idea I'm more that willing to adopt it.

**Comment by karstenBriksoft** [comment]
Technically a CGPoint is just a pair of x/y. But they are typically used to mean screen-coordinates. CoreLocation on the other hand uses CLLocationCoordinate2D to mean this pair of x/y is actually GPS coordinates. Now Shape-Files don't have a fixed projection and the points can be in any unit. That's why i'd suggest to introduce a point type like ShpPoint that is also just an x/y pair but it makes it clear that the coordinates are not to be confused with screen coordinates.

**Comment by nst** [comment]
What do you think about keeping CGPoints in order to avoid further casts or conversions, but call them MapPoints in order to avoid confusion between map and pixel coordinates?

```
typealias MapPoint = CGPoint
```

**Comment by karstenBriksoft** [comment]
sure, why not
